import type { MetadataRoute } from 'next';

/**
 * Installability. Chrome will not offer to install without a manifest carrying
 * name, start_url, a standalone display mode, and both a 192 and a 512 icon.
 *
 * The icon set is generated by scripts/gen-icons.mjs and committed, so this file
 * and the PNGs it points at can drift — regenerate rather than editing paths.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'KIBO — a shared aquarium for two',
    short_name: 'KIBO',
    description:
      'A shared aquarium for two. Presence without pressure: the tank keeps going whether or not anyone says anything.',
    // Deliberately the landing page, not a room. A room code belongs to a pair
    // of people, not to an installed app, and a stale code baked into someone's
    // home screen would open a tank they may have already left.
    start_url: '/',
    display: 'standalone',
    orientation: 'portrait',
    // Matches --background in globals.css and the themeColor in layout.tsx, so
    // the splash screen does not flash a different colour than the tank.
    background_color: '#081a26',
    theme_color: '#081a26',
    categories: ['lifestyle', 'social'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      // Separate entry rather than `purpose: 'any maskable'`. A single icon
      // declared as both gets padded by launchers that honour maskable and
      // shrunk by ones that don't, so it looks wrong in one place or the other.
      {
        src: '/icons/icon-512-maskable.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
